interface IPersonsList {
   icon: string;
   name: string;
   Rarity: string;
   Element: string;
   Weapon: string;
}

export const PersonsList: IPersonsList[] = [
   {
      icon: "./",
      name: "Albedo",
      Rarity: "5",
      Element: "Geo",
      Weapon: "qwe",
   },
   {
      icon: "----",
      name: "Al Haitham",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "ИКОНКА",
      name: "Aloy",
      Rarity: "РАНК",
      Element: "ЭЛЕМЕНТ",
      Weapon: "ОРУЖИЕ",
   },
   {
      icon: "",
      name: "Amber",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Arataki Itto",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Baizhu",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Barbara",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Beidou",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Bennett",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Candace",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Charlotte",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Chongyun",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Collei",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Cyno",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Dehya",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Diluc",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Diona",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Dori",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Eula",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Faruzan",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Fischl",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Freminet",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Furina",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Ganyu",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Gorou",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Hu Tao",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Jean",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Kaedehara Kazuha",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Kaeya",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Kamisato Ayaka",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Kamisato Ayato",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Kaveh",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Keqing",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Kirara",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Klee",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Kujou Sara",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Kuki Shinobu",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Layla",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Lisa",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Lynette",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Lyney",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Mika",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Mona",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Nahida",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Navia",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Neuvillette",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Nilou",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Ningguang",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Noelle",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Qiqi",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Raiden Shogun",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Razor",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Rosaria",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Sangonomiya Kokomi",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Sayu",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Shenhe",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Shikanoin Heizou",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Sucrose",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Tartaglia",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Thoma",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Tighnari",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Traveler",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Venti",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Wanderer",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Wriothesley",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Xiangling",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Xiao",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Xingqiu",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Xinyan",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Yae Miko",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Yanfei",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Yaoyao",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Yelan",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Yoimiya",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Yun Jin",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
   {
      icon: "",
      name: "Zhongli",
      Rarity: "",
      Element: "",
      Weapon: "",
   },
];
